java_binary(name='common-app',
             dependencies=[
               '3rdparty/java/org/log4j2:log4j',
              #  '3rdparty/java:lombok',
               "src/main/java/com/common:common-lib",
             ],
             sources=globs('*.java')
             )