java_binary(name='common-app_deploy.jar',
             dependencies=[
               #'3rdparty/java/org/log4j2:log4j',
               "src/main/java/com/common:common-lib",
               # "@maven//:junit_junit",
               # "@maven//:org_hamcrest_hamcrest_library",
               # "@maven//:org_apache_logging_log4j_log4j_core",
               # "@maven//:org_apache_logging_log4j_log4j_api",
               # "@maven//:com_lmax_disruptor",
               "@maven//:log4j_log4j",
             ],
             sources=globs('*.java')
             )