java_library(name='common-lib',
             dependencies=[
               '3rdparty/java/org/snappy:snappy',
               '3rdparty/java/org/log4j2:log4j',
             ],
             sources=globs('*.java')
             )