java_library(name='common-lib',
             dependencies=[
               '3rdparty/com/google/guava:guava',
               '3rdparty/java/org/snappy:snappy',
               '3rdparty/java/org/log4j2:log4j',
               '3rdparty/java:lombok',
             ],
             sources=globs('*.java'),
  )
             